export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  HANDOVER_EMPTY_SELECTION: "HANDOVER_EMPTY_SELECTION",
  HANDOVER_OWNER_REQUIRED: "HANDOVER_OWNER_REQUIRED",
  HANDOVER_NOTE_REQUIRED: "HANDOVER_NOTE_REQUIRED",
  VERSION_NO_CHANGES: "VERSION_NO_CHANGES",
  RISK_ITEM_NOT_FOUND: "RISK_ITEM_NOT_FOUND"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
