export const HANDOFF_ERROR_CODES = {
  OWNER_REQUIRED: "OWNER_REQUIRED",
  HANDOFF_TARGET_REQUIRED: "HANDOFF_TARGET_REQUIRED",
  CATEGORY_REQUIRED: "CATEGORY_REQUIRED",
  NO_OPEN_RISK_TO_HANDOFF: "NO_OPEN_RISK_TO_HANDOFF",
  RISK_NOT_FOUND: "RISK_NOT_FOUND"
} as const;

export type HandoffErrorCode = keyof typeof HANDOFF_ERROR_CODES;
